<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <ProjectReference Include="..\Arbor.DevPackages.Core\Arbor.DevPackages.Core.csproj" />
  </ItemGroup>
</Project>
